<div class="header" id="header">
	<div class="container">
		<div class="header-partner">
			<img class="header-partner__img" src="<?= publicdir("images/MTS_Logo_Brush_RU.svg") ?>">
		</div>

		<div class="header-info">
			<img class="header-info__logo" src="<?= publicdir("images/fox-logo.png") ?>">
			<div class="header-info__time">
				<span class="header-info__day">по понедельникам</span>
				22:00
			</div>
		</div>

		<div class="header-logo">
			<img class="header-logo__img" src="<?= publicdir("images/logo.png") ?>">
			<span class="header-logo__season">6 сезон</span>
		</div>

	</div>
</div>
