<div class="mts-connection" id="mts-connection">
    <h2>Телеканал <b>FOX</b> входит в пакет «Базовый» (кроме Москвы и&nbsp;МО) и&nbsp;в&nbsp;пакет «Ничего лишнего» <nobr>(в Москве и МО)</nobr> <a href="http://www.mts.ru/dom/?utm_source=fox_igra&amp;utm_medium=%D0%B1%D0%B0%D0%BD%D0%BD%D0%B5%D1%80&amp;utm_campaign=fox_v1_2016" target="_blank">Цифрового МТС ТВ</a></h2>
    <a href="#" class="content-button">Подключить</a>
</div>