<div class="top-block">
	<div class="top-block__link"><a href="#">О сериале</a></div>
	<div class="top-block__user">
		<div class="user">
			<div class="user__pic">
				<img src="">
			</div>
			<div class="user__exit">
				<a href="#"></a>
			</div>
		</div>
	</div>
</div>
<div class="page-error">
	<img class="page-error__img" src="<?= publicdir("images/404.png") ?>">
	<div class="page-error__txt">
		<p>Страница не существует, или она была удалена</p>
		<p>Вернуться на <a href="#">главную страницу</a></p>
	</div>
</div>
<div class="tricky-side-block">
	<?php include "src/views/helpers/mts-connection.phtml"; ?>
</div>