<div class="top-block">
	<div class="top-block__link"><a href="#">О сериале</a></div>
	<div class="top-block__user">
		<div class="user">
			<div class="user__pic">
				<img src="">
			</div>
			<div class="user__exit">
				<a href="#"></a>
			</div>
		</div>
	</div>
</div>
<div class="question">
	<div class="question__tl">Тот способ мести, что ведет к успеху:</div>
	<form class="form">
		<div class="form-group">
			<label class="radio-group" for="a1">
				<input type="radio" id="a1" name="question1">
				<span>Твой ум способен плавить льдины Винтерфелла</span>
			</label>
			<label class="radio-group" for="a2">
				<input type="radio" id="a2" name="question1">
				<span>Блеск золота решает все проблемы</span>
			</label>
			<label class="radio-group" for="a3">
				<input type="radio" id="a3" name="question1" checked>
				<span>Клинок — он храбрых сердцем друг</span>
			</label>
			<label class="radio-group" for="a4">
				<input type="radio" id="a4" name="question1">
				<span>Нетрудно мстить, коль есть господство средь людей</span>
			</label>
		</div>
		<button type="submit" class="content-button content-button--big">Далее</button>
	</form>
</div>
<div class="tricky-side-block">
	<?php include "src/views/helpers/mts-connection.phtml"; ?>
</div>
